//
// Created by cigan on 15.10.2020.
//

#ifndef PROBLEMSOLVINGARHITECTURE_VALIDATIONSIMPLEMENTATION_H
#define PROBLEMSOLVINGARHITECTURE_VALIDATIONSIMPLEMENTATION_H

#include "ValidationsDef.h"

void ValidateFile(FILE * FilePointer) {

    if (FilePointer == NULL)
        EXIT_FAILURE;
}

#endif //PROBLEMSOLVINGARHITECTURE_VALIDATIONSIMPLEMENTATION_H
